export const API_ENDPOINTS = {
  auth: {
    signIn: 'UsuarioWebLogin/UsuarioWebLogin',
    verifyMfa: 'UsuarioWeb/Mfa/ValidarLogin',
    mfaStatus: 'UsuarioWeb/Mfa/ObtenerEstado',
    mfaStart: 'UsuarioWeb/Mfa/IniciarActivacion',
    mfaConfirm: 'UsuarioWeb/Mfa/ConfirmarActivacion',
    mfaSessions: 'UsuarioWeb/Mfa/ObtenerSesionesActivas',
    signUp: 'UsuarioWebLogin/Registrar',
    refresh: 'UsuarioLogin/RefreshToken',
    me: 'UsuarioController/ObtenerPerfil',
    getProfile: 'PerfilUsuarioWeb/ObtenerPerfil',
    updateProfile: 'PerfilUsuarioWeb/ActualizarPerfil',
  },
  dashboard: {
    planConsumption: 'DashboardUsuarioWeb/PlanUsuarios',
    ticketsByRange: 'DashboardUsuarioWeb/TicketPorRango',
    ticketConsumption: 'DashboardUsuarioWeb/ConsumoTicket',
    topCompanies: 'DashboardUsuarioWeb/TopEmpresas',
    activityLog: 'DashboardUsuarioWeb/ObtenerLogActividad',
    latestTickets: 'DashboardUsuarioWeb/UltimosTickets',
    invoicePreparation: 'DashboardUsuarioWeb/PreparacionFacturacion',
  },
  wallet: {
    planSummary: 'PlanesUsuarioWeb/ObtenerPlanActualUsuario',
    subscriptionSummary: 'SuscripcionUsuarioWeb/ObtenerResumenSuscripcion',
    subscriptionStatus: 'SuscripcionUsuarioWeb/ObtenerEstadoSuscripcion',
    subscriptionTicketStatusSummary: 'SuscripcionUsuarioWeb/ObtenerResumenEstatusTickets',
    subscriptionPlanBenefits: 'SuscripcionUsuarioWeb/ObtenerBeneficiosPlan',
    usage: 'ProfileManagement/UsoActual',
    cards: 'StripeUsuarioWeb/ListarMetodosPagoUsuario',
    stripePublicConfig: 'StripeUsuarioWeb/ObtenerConfiguracionPublica',
    createSetupIntent: 'StripeUsuarioWeb/CrearSetupIntent',
    invoices: 'StripeUsuarioWeb/ListarHistorialPagosUsuario',
    alerts: 'ProfileManagement/Notificaciones',
    taxInfo: 'Contribuyentes/ObtenerDatosFiscales',
    security: 'UsuarioController/Seguridad',
    plans: 'PlanesUsuarioWeb/ObtenerPlanesBeneficiosVinculacionUsuario',
    setDefaultCard: 'StripeUsuarioWeb/EstablecerMetodoPagoDefault',
    removeCard: 'StripeUsuarioWeb/EliminarMetodoPago',
    toggleAutoRenew: 'SuscripcionUsuarioWeb/ActualizarRenovacionAutomatica',
    retryPayment: 'Suscripcion/ReintentarPago',
    updateTaxInfo: 'Contribuyentes/ActualizarDatosFiscales',
    changePlan: 'StripeUsuarioWeb/CobrarCambioPlanUsuario',
    cancelPlan: 'SuscripcionUsuarioWeb/CancelarSuscripcion',
  },
  contributors: {
    global: 'ContribuyentesUsuarioWeb/ObtenerContribuyentesGlobales',
    favorites: 'ContribuyentesUsuarioWeb/ObtenerContribuyentesFavoritos',
    addFavorite: 'ContribuyentesUsuarioWeb/AgregarFavorito',
    removeFavorite: 'ContribuyentesUsuarioWeb/QuitarFavorito',
    extractCsf: 'ContribuyentesUsuarioWeb/ExtraerCsf',
    saveCsf: 'ContribuyentesUsuarioWeb/GuardarCsf',
  },
  support: {
    headerSummary: 'SoporteUsuarioWeb/ResumenCabecera',
    recentTickets: 'SoporteUsuarioWeb/TicketsRecientes',
    historyTickets: 'SoporteUsuarioWeb/HistorialTickets',
    ticketDetail: 'SoporteUsuarioWeb/ObtenerDetalleTicket',
    ticketImage: 'SoporteUsuarioWeb/DescargarImagenTicket',
    quickActions: 'Soporte/AccionesRapidas',
    guides: 'Soporte/Guias',
    faqs: 'Soporte/Faqs',
    legalResources: 'Soporte/RecursosLegales',
    createTicket: 'SoporteUsuarioWeb/CrearTicket',
  },
  tickets: {
    list: 'Ticket/ObtenerTickets',
    retry: 'Ticket/Reintentar',
    exportCsv: 'Ticket/ExportarCsv',
    readTicket: 'TicketsUsuarioWeb/LecturaTicket',
    saveExtractedTickets: 'TicketsUsuarioWeb/GuardarTicketsExtraidos',
    associatedContributors: 'TicketsUsuarioWeb/ContribuyentesAsociadosUsuario',
    statusSummary: 'TicketsUsuarioWeb/EstatusTickets',
    userListById: 'TicketsUsuarioWeb/ListaTicketsId',
    viewTicket: 'TicketsUsuarioWeb/ObtenerVerTicket',
    downloadTicketImage: 'TicketsUsuarioWeb/DescargarImagenTicket',
  },
} as const;


